# 导航栏设置
menu:
  首页: /
  文章: /archives
  标签: /tags
  关于: /about

# 博客建设时间：显示在页脚
blog_since: 2015

# 网站链接：显示在左上角
site_url: geekwen.com

# 网站logo链接：显示在左上角
logo_url: /images/logo.png

# 首页正文内容：分别对应第一行和第二行
index_content:
  1: Geekwen
  2: 一个前端开发工程师的博客