# 导航栏设置
menu:
  首页: /
  文章: /archives
  标签: /tags
  关于: /about

# 博客建设时间：显示在页脚
blog_since: 2015

# 网站链接：显示在左上角
site_url: geekwen.com

# 网站logo链接：显示在左上角
logo_url: /images/logo.png

# 首页正文内容：分别对应第一行和第二行
index_content:
  1: Geekwen
  2: 一个前端开发工程师的博客

# 标签描述
tag:
  webpack: <a href="https://doc.webpack-china.org" target="_blank">webpack</a> 是一个现代 JavaScript 应用程序的模块打包器(module bundler)。
  node.js: <a href="https://nodejs.org" target="_blank">Node.js</a> 是一个能够在服务器端运行JavaScript的开放源代码、跨平台JavaScript运行环境。